# This workflow works, but C* does not start in time for these tests to work in a reasonable manner.
name: Build and test
on:
  # Build PRs
  pull_request: ~
  # On push event
  push:
    # Build only changes pushed into the `master` branch.
    branches: ~
    # Ignore documentation changes (Netlify will handle this)
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '**/*.md'

jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        java: [ 11, 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Build
        run: gradle build check --no-daemon --stacktrace
